Repository KyberNetwork/widget-woocommerce, pull requests merged in 2018-10, with the labels that each got.

#7 Update version field
  admin/partials/kyber-settings.php
Labels: bug

#12 Added license badge
  README.md
Labels: hacktoberfest

#15 Added German translations
  languages/woo-kyber-payment-de_CH.mo
  languages/woo-kyber-payment-de_CH.po
  languages/woo-kyber-payment-de_CH_informal.mo
  languages/woo-kyber-payment-de_CH_informal.po
  languages/woo-kyber-payment-de_DE.mo
  languages/woo-kyber-payment-de_DE.po
  languages/woo-kyber-payment-de_DE_formal.mo
  languages/woo-kyber-payment-de_DE_formal.po
Labels: enhancement, hacktoberfest

#14 Added Spanish translation # 13
  languages/woo-kyber-payment_es.mo
  languages/woo-kyber-payment_es.po
Labels: enhancement, hacktoberfest

#18 Added Polish (PL) translation
  languages/woo-kyber-payment-pl_PL.mo
  languages/woo-kyber-payment-pl_PL.po
Labels: enhancement, hacktoberfest

#21 Fixed a typo
  languages/woo-kyber-payment.mo
  languages/woo-kyber-payment.po
Labels: enhancement

#22 Added Slovene translations (sl-SI)
  composer.json
  languages/woo-kyber-payment-sl_SI.mo
  languages/woo-kyber-payment-sl_SI.po
Labels: enhancement, hacktoberfest
